# Generated by Django 5.0.1 on 2024-08-11 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_clienttype_identificationnumber_identificationtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
                ('Category', models.CharField(choices=[('Service', 'Service'), ('Product', 'Product'), ('Consulting', 'Consulting')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.eventtype')),
            ],
        ),
    ]
