# Generated by Django 5.0.1 on 2024-08-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billingevent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingevent',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
