# Generated by Django 5.0.1 on 2024-01-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_accountuser_corporatecontact_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicSDKConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=120)),
                ('Database', models.CharField(max_length=12)),
                ('Host', models.CharField(max_length=120)),
                ('EndpointURL', models.CharField(max_length=200)),
                ('UserCode', models.CharField(max_length=12)),
                ('DatalakeInstance', models.CharField(blank=True, max_length=25, null=True)),
                ('GoogleProjectID', models.CharField(blank=True, max_length=25, null=True)),
                ('GoogleJSONFilename', models.CharField(blank=True, max_length=60, null=True)),
                ('GoogleJSONFile', models.TextField(blank=True, null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
