# Generated by Django 5.0.1 on 2024-01-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_corporatecontact_account_alter_account_naicscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epicsdkconfiguration',
            name='Database',
            field=models.CharField(max_length=20),
        ),
    ]
