# Generated by Django 5.0.1 on 2024-06-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address1',
            field=models.CharField(default='Test', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='Address2',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='City',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='State',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='Zip',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='Attachments',
            field=models.ManyToManyField(blank=True, to='acord.attachment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='LinesOfBusiness',
            field=models.ManyToManyField(blank=True, to='acord.linesofbusiness'),
        ),
    ]
