# Generated by Django 5.0.1 on 2024-05-28 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_epicsdkconfiguration_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMSObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AMSObjectValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AMSField', models.CharField(max_length=255)),
                ('Required', models.BooleanField()),
                ('AMSType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsforms.amsobjecttype')),
            ],
        ),
        migrations.CreateModel(
            name='AMSObjectValueDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DefaultValue', models.CharField(max_length=255)),
                ('AMSObjectValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsforms.amsobjectvalue')),
            ],
        ),
        migrations.CreateModel(
            name='AMSType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AMS', models.CharField(choices=[('EPIC', 'Epic')], max_length=255)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.AddField(
            model_name='amsobjecttype',
            name='AMSType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsforms.amstype'),
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormTitle', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.AddField(
            model_name='amsobjecttype',
            name='FormDefinition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsforms.formdefinition'),
        ),
        migrations.CreateModel(
            name='FormToAMSValueMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormField', models.CharField(max_length=255)),
                ('AMSObjectType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsforms.amsobjecttype')),
                ('AMSObjectValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsforms.amsobjectvalue')),
            ],
        ),
        migrations.CreateModel(
            name='JotformParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormID', models.IntegerField()),
                ('Username', models.CharField(max_length=255)),
                ('FormDefinition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsforms.formdefinition')),
            ],
        ),
    ]
