# Generated by Django 5.0.1 on 2024-05-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotformparameters',
            name='FormID',
            field=models.CharField(max_length=255),
        ),
    ]
