# Generated by Django 5.0.1 on 2024-05-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsforms', '0003_amsobjecttype_amsobjecttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jotformparameters',
            options={'verbose_name': 'Jotform Parameters', 'verbose_name_plural': 'Jotform Parameters'},
        ),
        migrations.RenameField(
            model_name='amsobjectvalue',
            old_name='AMSType',
            new_name='AMSObjectType',
        ),
    ]
