# Generated by Django 5.0.1 on 2024-05-28 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsforms', '0004_alter_jotformparameters_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amsobjectvaluedefault',
            name='AMSObjectType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amsforms.amsobjecttype'),
            preserve_default=False,
        ),
    ]
