# Generated by Django 5.0.1 on 2024-06-17 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsforms', '0005_amsobjectvaluedefault_amsobjecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amsobjecttype',
            name='AMSObjectType',
            field=models.CharField(choices=[('Activity', 'Activity'), ('Client', 'Client'), ('Opportunity', 'Opportunity')], max_length=255),
        ),
        migrations.CreateModel(
            name='CognitoParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormID', models.CharField(max_length=255)),
                ('InternalName', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('FormDefinition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsforms.formdefinition')),
            ],
            options={
                'verbose_name': 'Cognito Parameters',
                'verbose_name_plural': 'Cognito Parameters',
            },
        ),
    ]
