# Generated by Django 5.0.1 on 2024-06-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsforms', '0006_alter_amsobjecttype_amsobjecttype_cognitoparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amsobjecttype',
            name='AMSObjectType',
            field=models.CharField(choices=[('Activity', 'Activity'), ('Client', 'Client'), ('Opportunity', 'Opportunity'), ('Policy', 'Policy')], max_length=255),
        ),
    ]
