# Generated by Django 5.0.1 on 2024-08-15 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_accounttokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='SambaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientID', models.CharField(max_length=120)),
                ('ClientSecret', models.CharField(max_length=240)),
                ('APIKey', models.CharField(max_length=240)),
                ('URL', models.CharField(max_length=240)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
