# Generated by Django 5.0.1 on 2024-01-19 23:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.IntegerField(blank=True, null=True)),
                ('AccountTypeCode', models.CharField(blank=True, max_length=10, null=True)),
                ('ActivityCode', models.CharField(blank=True, max_length=4, null=True)),
                ('ActivityID', models.IntegerField(blank=True, null=True)),
                ('AgencyCode', models.CharField(blank=True, max_length=4, null=True)),
                ('AssociatedToID', models.IntegerField(blank=True, null=True)),
                ('AssociatedToType', models.CharField(blank=True, max_length=30, null=True)),
                ('BranchCode', models.CharField(blank=True, max_length=4, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Priority', models.CharField(blank=True, max_length=10, null=True)),
                ('Timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('WhoOwnerCode', models.CharField(blank=True, max_length=10, null=True)),
                ('CategoryID', models.IntegerField(blank=True, null=True)),
                ('GeneralLedgerItemIDForAssociatedToID', models.IntegerField(blank=True, null=True)),
                ('EnteredDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('AttachmentsYesNo', models.BooleanField(blank=True, null=True)),
                ('LastUpdatedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('AssociatedToGUID', models.CharField(blank=True, max_length=60, null=True)),
                ('LineID', models.IntegerField(blank=True, null=True)),
                ('SMS', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityCode', models.CharField(max_length=4)),
                ('Description', models.CharField(blank=True, max_length=120, null=True)),
                ('Category', models.CharField(blank=True, max_length=120, null=True)),
                ('PriorityCode', models.CharField(blank=True, max_length=1, null=True)),
                ('Active', models.BooleanField(blank=True, null=True)),
                ('IsClientVisible', models.BooleanField(blank=True, null=True)),
                ('IsClientEditable', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activity Types',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('DueDate', models.DateField(blank=True, null=True)),
                ('DueTime', models.DateTimeField(blank=True, null=True)),
                ('Flag', models.CharField(blank=True, max_length=20, null=True)),
                ('Owner', models.CharField(blank=True, max_length=12, null=True)),
                ('OwnerType', models.CharField(blank=True, max_length=30, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('TaskID', models.IntegerField(blank=True, null=True)),
                ('OrderNumber', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloseDetailValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActualCost', models.IntegerField(blank=True, null=True)),
                ('ActualTimeHours', models.IntegerField(blank=True, null=True)),
                ('ActualTimeMinutes', models.IntegerField(blank=True, null=True)),
                ('ClosedReason', models.CharField(blank=True, max_length=30, null=True)),
                ('ClosedStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('IgnoreOpenTasks', models.BooleanField(blank=True, null=True)),
                ('AverageCost', models.IntegerField(blank=True, null=True)),
                ('AverageTimeHours', models.IntegerField(blank=True, null=True)),
                ('AverageTimeMinutes', models.IntegerField(blank=True, null=True)),
                ('Duration', models.IntegerField(blank=True, null=True)),
                ('Activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='DetailValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactName', models.CharField(blank=True, max_length=60, null=True)),
                ('ContactNumberEmail', models.CharField(blank=True, max_length=60, null=True)),
                ('ContactVia', models.CharField(blank=True, max_length=10, null=True)),
                ('FollowUpEndDate', models.DateField(blank=True, null=True)),
                ('FollowUpEndTime', models.TimeField(blank=True, null=True)),
                ('FollowUpStartDate', models.DateField(auto_now_add=True, null=True)),
                ('FollowUpStartTime', models.TimeField(blank=True, null=True)),
                ('IssuingCompanyLookupCode', models.CharField(blank=True, max_length=10, null=True)),
                ('PremiumPayableLookupCode', models.CharField(blank=True, max_length=10, null=True)),
                ('PremiumPayableTypeCode', models.CharField(blank=True, max_length=10, null=True)),
                ('ReminderDate', models.DateField(blank=True, null=True)),
                ('ReminderTime', models.TimeField(blank=True, null=True)),
                ('ContactPhoneCountryCode', models.CharField(blank=True, max_length=10, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('AmountQualifier', models.CharField(blank=True, max_length=10, null=True)),
                ('Update', models.CharField(blank=True, max_length=10, null=True)),
                ('ContactID', models.IntegerField(blank=True, null=True)),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='IndioSubmissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarrierSubmissionID', models.IntegerField(blank=True, null=True)),
                ('SubmissionID', models.IntegerField(blank=True, null=True)),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetailValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.detailvalue')),
            ],
        ),
        migrations.CreateModel(
            name='ServicingContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='AccountServicingContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=10, null=True)),
                ('EmailAddress', models.CharField(blank=True, max_length=120, null=True)),
                ('Extension', models.CharField(blank=True, max_length=4, null=True)),
                ('Name', models.CharField(blank=True, max_length=120, null=True)),
                ('ServicingRole', models.CharField(blank=True, max_length=30, null=True)),
                ('ServicingContacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.servicingcontacts')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionName', models.CharField(blank=True, max_length=10, null=True)),
                ('Value', models.IntegerField(blank=True, null=True)),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.taskitem')),
            ],
        ),
        migrations.CreateModel(
            name='NoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessLevel', models.CharField(blank=True, max_length=20, null=True)),
                ('Flag', models.CharField(blank=True, max_length=20, null=True)),
                ('NoteID', models.IntegerField(blank=True, null=True)),
                ('NoteText', models.TextField(blank=True, max_length=1000, null=True)),
                ('Notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.notes')),
                ('TaskNotes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.tasknotes')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
        ),
        migrations.AddField(
            model_name='taskitem',
            name='Tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.tasks'),
        ),
        migrations.CreateModel(
            name='WhoOwnerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionName', models.CharField(blank=True, max_length=20, null=True)),
                ('Value', models.CharField(blank=True, max_length=20, null=True)),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
            ],
        ),
    ]
