# Generated by Django 5.0.1 on 2024-01-20 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JotformConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormTitle', models.CharField(max_length=120)),
                ('FormID', models.CharField(max_length=120)),
                ('FieldAccountID', models.CharField(blank=True, max_length=60, null=True)),
                ('AccountID', models.CharField(blank=True, max_length=60, null=True)),
                ('FieldAssociatedToID', models.CharField(blank=True, max_length=60, null=True)),
                ('AssociatedToID', models.CharField(blank=True, max_length=60, null=True)),
                ('OwnerType', models.CharField(blank=True, max_length=30, null=True)),
                ('OwnerCode', models.CharField(blank=True, max_length=30, null=True)),
                ('Priority', models.CharField(blank=True, max_length=10, null=True)),
                ('AccountTypeCode', models.CharField(blank=True, max_length=4, null=True)),
                ('AssociatedToType', models.CharField(blank=True, max_length=20, null=True)),
                ('ActivityType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.activitytype')),
            ],
        ),
    ]
