# Generated by Django 5.0.1 on 2024-01-20 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_epicsdkconfiguration_database'),
        ('webform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jotformconfiguration',
            name='Account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.account'),
            preserve_default=False,
        ),
    ]
